default: &default
  adapter: 'postgresql'
  encoding: 'unicode'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 'app_test'
  host: 'db'
  username: 'postgres'
  password: 'password'

test:
  <<: *default
  database: 'app_test'
  host: 'db'
  username: 'postgres'
  password: 'password'

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:database_url) %>